version: '3'

services:
    redis:  # CAUTION: docker error!!
        #image: cojam/redis:5.0.5.1-alpine-3.10
        image: cojam/redis:4.0.9.0-ubuntu-18.04
        container_name: redis
        #ports:
            #- 6379:6379
        volumes:
            - ./conf/redis/redis.conf:/etc/redis/redis.conf
            - ./log/redis:/var/log/redis
        networks:
            - backend
    niltalk:
        image: cojam/niltalk:0.0.0.1-alpine-3.10
        container_name: niltalk
        #ports:
            #- 4008:4008
        volumes:
            - ./conf/niltalk/config.json:/app/config.json
            - ./log/niltalk:/var/log/niltalk
        networks:
            - backend
        depends_on:
            - redis
    caddy:
        image: cojam/caddy:1.0.4.1-alpine-3.10
        container_name: caddy
        ports:
            #- 4008:4008
            - 4009:4009
        volumes:
            - ./conf/caddy/Caddyfile:/etc/Caddyfile
            - ./log/caddy:/var/log/caddy
        networks:
            - backend
        depends_on:
            - niltalk

networks:
    backend:
    


