#
# Makefile for chat in go
#
usage:
	@echo "usage: make [edit|build|run]"

build b:
	@echo "> make (build) [client|server]"

build-client bc:
	go build -o client client/*.go

build-server bs:
	go build -o server server/*.go



git update gu:
	cd ..; make gu
