#
# Makefile for chat
#
PROG=wschat
usage:
	@echo "usage: make [edit|buil|run]"

edit e:
	vi $(PROG).go

build b:
	go build -o $(PROG)

run r:
	go run --race $(PROG).go




git-update gu:
	cd ..; make gu

